$('.one-time').slick({
  dots: true,
  arrows: false,
  touchMove: true,
  autoplay: true,
  speed: 5000,
  autoplaySpeed: 5000,
  infinite: true,
  speed: 3000,
  infinite: true,
  pauseOnFocus: true,
  pauseOnHover: true,
  pauseOnDotsHover: true,
  slidesToShow: 1,
  adaptiveHeight: true,
});
